const c=document.querySelector('#universe'),x=c.getContext('2d'),chapters=[...document.querySelectorAll('.chapter')],marks=[...document.querySelectorAll('.progress i')],skills=[...document.querySelectorAll('.skill')],signal=document.querySelector('.signal');
let w,h,dpr,stars=[],matter=[],scroll=0,target=0,time=0,mouse={x:.5,y:.5},focused=-1,lockedAngle=null;
const max=()=>Math.max(w,h),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function setup(){dpr=Math.min(devicePixelRatio,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';x.setTransform(dpr,0,0,dpr,0,0);let n=w<700?280:680,m=w<700?250:580;stars=Array.from({length:n},()=>({x:Math.random()*w,y:Math.random()*h,z:Math.random(),a:.12+Math.random()*.58}));matter=Array.from({length:m},()=>({r:80+Math.pow(Math.random(),.52)*max()*.77,a:Math.random()*7,dr:.012+Math.random()*.045,seed:Math.random()*99,side:Math.random()>.17?1:-1,size:.25+Math.random()*1.5}))}
function P(){return clamp(scroll/(document.body.scrollHeight-innerHeight),0,1)}
function arc(cx,cy,r,p){/* warped, bright disk: separate turbulent streamlines make it feel alive */x.save();x.globalCompositeOperation='lighter';for(let k=0;k<8;k++){let heat=k/7,g=x.createLinearGradient(cx-r*1.7,cy,cx+r*1.7,cy);g.addColorStop(0,'rgba(110,27,4,0)');g.addColorStop(.42,'rgba(255,128,25,'+(.02+heat*.035)+')');g.addColorStop(.68,'rgba(255,241,199,'+(.06+heat*.028)+')');g.addColorStop(1,'rgba(148,35,4,0)');x.strokeStyle=g;x.lineWidth=3+k*4;x.beginPath();x.ellipse(cx,cy,r*(1.03+k*.105),r*(.15+k*.017),-.08,0,Math.PI*2);x.stroke()}/* gravitationally lensed far side rising above the shadow */for(let k=0;k<5;k++){x.strokeStyle='rgba(255,'+(170+k*16)+','+(75+k*22)+','+(.055-k*.007)+')';x.lineWidth=2+k*2;x.beginPath();x.ellipse(cx,cy-r*(.28+k*.035),r*(.90+k*.055),r*(.095+k*.012),-.08,Math.PI*1.02,Math.PI*1.98);x.stroke()}let hot=x.createLinearGradient(cx-r*1.3,cy,cx+r*1.3,cy);hot.addColorStop(0,'rgba(255,161,46,.03)');hot.addColorStop(.58,'rgba(255,230,175,.32)');hot.addColorStop(.78,'rgba(255,117,20,.18)');hot.addColorStop(1,'rgba(255,130,27,.02)');x.strokeStyle=hot;x.lineWidth=Math.max(3,r*.075);x.beginPath();x.ellipse(cx,cy,r*1.2,r*.2,-.08,.08,Math.PI-.1);x.stroke();x.restore()}
function draw(){let p=P(),escape=clamp((p-.84)/.16,0,1),cx=w*(.5+(mouse.x-.5)*.012),cy=h*(.51+(mouse.y-.5)*.012),zoom=.33+p*1.94-escape*.7,r=Math.min(w,h)*(.13+p*.135-escape*.05);x.fillStyle='#020201';x.fillRect(0,0,w,h);
for(let s of stars){let dx=s.x-cx,dy=s.y-cy,d=Math.hypot(dx,dy),pull=clamp(1-d/(max()*.63),0,1),a=Math.atan2(dy,dx)+pull*pull*.14*Math.sin(Math.atan2(dy,dx)*2),rr=d+pull*20*zoom;x.fillStyle='rgba(205,215,224,'+(s.a*(1-p*.65+escape*.45))+')';let z=s.z<.25?1:1.5;x.fillRect(cx+Math.cos(a)*rr,cy+Math.sin(a)*rr,z,z)}
x.save();x.globalCompositeOperation='lighter';for(let q of matter){let pull=clamp(1-q.r/(max()*.8),0,1),speed=.00035+(110/q.r)*.009;q.a+=speed*(1+p*3.4)*q.side;q.r-=q.dr*(1+p*3.8)*(1+pull*13);if(q.r<r*.72){q.r=max()*(.42+Math.random()*.43);q.a+=1.5+Math.random()*2}let px=cx+Math.cos(q.a)*q.r*zoom*1.34,py=cy+Math.sin(q.a)*q.r*zoom*.28,near=Math.hypot(px-mouse.x*w,py-mouse.y*h);q.a+=q.side*clamp(1-near/150,0,1)*.0015;let heat=clamp(1-q.r/(max()*.34),0,1),alpha=.08+pull*.72,xp=cx+Math.cos(q.a)*q.r*zoom*1.34,yp=cy+Math.sin(q.a)*q.r*zoom*.28,tail=.018+pull*.14;x.strokeStyle=q.seed%5<1?'rgba(139,179,205,'+(alpha*.28)+')':'rgba(255,'+(130+Math.floor(heat*105))+','+(35+Math.floor(heat*135))+','+alpha+')';x.lineWidth=q.size*(1+heat*2);x.beginPath();x.moveTo(xp,yp);x.lineTo(cx+Math.cos(q.a-tail)*q.r*zoom*1.34,cy+Math.sin(q.a-tail)*q.r*zoom*.28);x.stroke()}x.restore();arc(cx,cy,r,p);
let halo=x.createRadialGradient(cx,cy,r*.66,cx,cy,r*1.35);halo.addColorStop(0,'rgba(0,0,0,0)');halo.addColorStop(.68,'rgba(255,140,27,.09)');halo.addColorStop(1,'rgba(255,122,18,0)');x.fillStyle=halo;x.beginPath();x.arc(cx,cy,r*1.42,0,7);x.fill();x.fillStyle='#000';x.beginPath();x.arc(cx,cy,r*.79,0,7);x.fill();/* compressed photon arcs at the rim */x.save();x.globalCompositeOperation='lighter';for(let n=0;n<3;n++){x.strokeStyle='rgba(255,228,171,'+(.18-n*.045)+')';x.lineWidth=1;x.beginPath();x.ellipse(cx,cy,r*(.80+n*.025),r*(.79+n*.023),0,-.75,.15);x.stroke()}x.restore();
placeSkills(cx,cy,r,p,escape);time+=16;requestAnimationFrame(draw)}
function placeSkills(cx,cy,r,p,escape){skills.forEach((el,i)=>{let base=[-.82,2.23,.43][i],speed=[.000020,.000052,.000036][i],angle=i===focused&&lockedAngle!==null?lockedAngle:base+time*speed*(1+p*2.8),rad=r*[3.35,1.95,2.62][i]*(1-p*.14),depth=(Math.sin(angle)+1)/2,px=cx+Math.cos(angle)*rad,py=cy+Math.sin(angle)*rad*(.28+depth*.08)-p*25,scale=.82+depth*.27+(i===focused?.14:0);el.style.left=px+'px';el.style.top=py+'px';el.style.opacity=(.46+depth*.54)*(1-escape*.35);el.style.zIndex=depth>.55?6:4;el.style.transform='translate(-50%,-50%) scale('+scale+')';el.classList.add('visible')})}
function tick(){target=scrollY;scroll+=(target-scroll)*.085;let p=P(),stage=Math.min(4,Math.floor(p*5.1));marks.forEach((m,i)=>m.classList.toggle('on',i===Math.min(4,stage)));chapters.forEach((s,i)=>s.classList.toggle('active',i===stage));requestAnimationFrame(tick)}
function show(el){focused=skills.indexOf(el);let p=P(),i=focused;lockedAngle=[-.82,2.23,.43][i]+time*[.000020,.000052,.000036][i]*(1+p*2.8);skills.forEach(s=>s.classList.remove('focus'));el.classList.add('focus');signal.querySelector('strong').textContent=el.dataset.name.toUpperCase();signal.querySelector('p').textContent=el.dataset.detail;signal.classList.add('show')}
function unfocus(){focused=-1;lockedAngle=null;signal.classList.remove('show');skills.forEach(s=>s.classList.remove('focus'))}
skills.forEach(el=>{el.addEventListener('mouseenter',()=>show(el));el.addEventListener('focus',()=>show(el));el.addEventListener('mouseleave',unfocus);el.addEventListener('blur',unfocus)});addEventListener('mousemove',e=>mouse={x:e.clientX/w,y:e.clientY/h});addEventListener('resize',setup);addEventListener('scroll',()=>target=scrollY,{passive:true});setup();tick();draw();
